### PR TITLE
switch to jbuilder

### PR DESCRIPTION
**Pull request by vbmithr**
Could you please try @copy . This is a buildsystem change to jbuilder. I really like it and it compiles blazing fast compared to ocamlbuild.

This PR is extremely messy. Apart from the switch to async, it also contain code to remove the ppx extension of lwt that is not supported by jbuilder (and that we used very rarely anyway). I just changed code to make it compile, without (hopefully) changing any functionality.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Also, it would be really nice to get rid of the depopts and have explicit packages opam subpackages for websocket, websocket-lwt, websocket-async.

How does the jbuilder generated META file look like btw? That might force some backwards compatibility issues for users.

**Comment by vbmithr** [comment]
@copy It does not seem to be possible to use the library namespace feature of jbuilder on modules that have different set of dependencies. Correct me if I'm wrong.

@rgrinberg Gonna try this soon!

**Comment by rgrinberg** [comment]
@vbmithr just in case you haven't seen this before, there's a little trick to generate META files that are backwards compatible. I got this from hhugo's port of jsoo. Check out the `META.cohttp.template` file in https://github.com/mirage/ocaml-cohttp/pull/533 for example

**Comment by copy** [comment]
> It does not seem to be possible to use the library namespace feature of jbuilder on modules that have different set of dependencies. Correct me if I'm wrong.

That's fine then. May I suggest at least renaming the modules to `Websocket_rng*`, so that they don't clash with other libraries (#69)? We could also consider getting rid of the Rng modules, since they're just one-liners and the `random_string` parameter is pretty much self-explanatory.

**Comment by vbmithr** [comment]
This should be fine now, I have fixed things according to your recommendations. @copy Could you review it again?

**Comment by copy** [comment]
Looks good, thanks. I can't pin it though, I'm assuming I need to pin in the build directory since the opam file is there?

```
opam pin add _build/install/default/lib/websocket/
```

Results in this error:

```
Error: I don't know about package websocket (passed through --only-packages/--release)
```

**Comment by vbmithr** [comment]
On 23/04/2017 22:13, Fabian wrote:
> Looks good, thanks. I can't pin it though, I'm assuming I need to pin in
> the build directory since the opam file is there?

No, you can pin it as usual, at the root of the project. I did not have
any problems pinning this package.

**Comment by cornop** [comment]
> No, you can pin it as usual, at the root of the project. I did not have
any problems pinning this package.

This works, but it doesn't install `websocket-lwt`, which is required for `websocket.lwt`:

```
ocamlfind: Package `websocket-lwt' not found - required by `websocket.lwt'
````

**Comment by copy** [comment]
> No, you can pin it as usual, at the root of the project. I did not have
any problems pinning this package.

This works, but it doesn't install websocket-lwt, which is required for websocket.lwt:

```
ocamlfind: Package `websocket-lwt' not found - required by `websocket.lwt'
```

**Comment by vbmithr** [comment]
Yeah, you have to `opam pin add websocket-lwt <ocaml-websocket-directory>`

**Comment by copy** [comment]
> Yeah, you have to opam pin add websocket-lwt <ocaml-websocket-directory>

Got it, thanks. Everything's good.

**Pull request closed without merging**
